---
title: "Assignment 1: Identify a Dataset"
author: "Meghan Casey"
date: September 3, 2020
output: 
  html_document:
    theme: "cosmo" 
    highlight: "tango"
---

### Load Libraries
```{r Load Libraries} 
library(tidycensus)
library(tidyverse)
```

### Mass Renters
```{r Mass Renters} 
hh_data_MA <- get_pums(variables = c("TEN", 
                                  "YBL", 
                                  "BDSP", 
                                  "GRNTP", 
                                  "BLD",
                                  "NP",
                                  "MV",
                                  "HHT"),
                        state = "MA",
                        year = 2018, 
                        survey = "acs1",
                        recode = TRUE) %>%
  filter(TEN_label == "Rented") %>%
  mutate(age_struct = case_when(
    YBL_label == "1939 or earlier" ~ 100,
    YBL_label == "1940 to 1949" ~ 73,
    YBL_label == "1950 to 1959" ~ 63,
    YBL_label == "1960 to 1969" ~ 53,
    YBL_label == "1970 to 1979" ~ 43,
    YBL_label == "1980 to 1989" ~ 33,
    YBL_label == "1990 to 1999" ~ 23,
    YBL_label == "2000 to 2004" ~ 16,
    YBL_label == "2005" ~ 13,
    YBL_label == "2006" ~ 12,
    YBL_label == "2007" ~ 11,
    YBL_label == "2008" ~ 10,
    YBL_label == "2009" ~ 9,
    YBL_label == "2010" ~ 8,
    YBL_label == "2011" ~ 7,
    YBL_label == "2012" ~ 6,
    YBL_label == "2013" ~ 5,
    YBL_label == "2014" ~ 4,
    YBL_label == "2015" ~ 3,
    YBL_label == "2016" ~ 2,
    YBL_label == "2017" ~ 1,
    YBL_label == "2018" ~ 0)) %>%
    mutate(move_in = case_when(
    MV_label == "10 to 19 years" ~ 15,
    MV_label == "12 months or less" ~ 1,
    MV_label == "13 to 23 months" ~ 2,
    MV_label == "2 to 4 years" ~ 3,
    MV_label == "20 to 29 years" ~ 25,
    MV_label == "30 years or more" ~ 30,
    MV_label == "5 to 9 years" ~ 7)) %>%
  select(age_struct, BDSP, GRNTP, BLD_label, NP, move_in, HHT_label)
```
  
### Save Dataset

```{r Save Dataset} 
write_csv(hh_data_MA, "households_ma.csv")
```
